version: '3'
services:
  selenoid:
    volumes:
      - "$PWD:$PWD"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/tmp/video:/tmp/video:z"
  test:
    volumes:
      - "$PWD:$PWD"
      - "/var/jenkins_home:/var/jenkins_home:z"

